# <font face = 'Impact' color = '#FFAEBC' > Loading, Organizing, and Storing Data Two <font/>
#### <font face = 'Times New Roman' color = '#B5E5CF'> License: GPL v3.0<font/>
#### <font face = 'Times New Roman' color = '#B5E5CF'> Author and Trainer: Paolo Hilado MSc. (Data Science)<font/>
In this section, we’ll learn how to load datasets into Python using the pandas library, focusing on common file formats like CSV. Once the data is loaded into a DataFrame, we’ll explore simple techniques to identify missing values. This includes checking for NaN entries, summarizing null counts per column, and using visual or logical methods to detect incomplete rows. Spotting missing data early is an important step in ensuring data quality before analysis or modeling.

In [ ]:
# Import the necessary libraries
import pandas as pd
import numpy as np
import os

In [ ]:
#Checking out the current working directory
print(os.getcwd())

/content

In [ ]:
os.chdir('/content/sample_data')

In [ ]:
#Loading a .Sav file and assigning it to a variable
#We will open and work on "Bank.sav"
import pandas as pd
df = pd.read_excel("PracticeTest.xlsx")
df

,Sex,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
0,Female,1.0,2.0,1.0,5.0,2.0,3.0,1.0,5.0,4.0,...,4.0,2.0,4.0,3.0,4.0,1.0,2.0,1.0,2.0,4.0
1,Female,5.0,5.0,1.0,4.0,5.0,4.0,5.0,5.0,5.0,...,5.0,1.0,5.0,3.0,5.0,4.0,3.0,1.0,3.0,3.0
2,Male,2.0,5.0,1.0,3.0,3.0,2.0,5.0,1.0,5.0,...,2.0,2.0,3.0,4.0,2.0,5.0,3.0,2.0,1.0,2.0
3,Male,2.0,4.0,1.0,5.0,2.0,3.0,2.0,2.0,2.0,...,2.0,2.0,3.0,4.0,2.0,4.0,5.0,1.0,3.0,2.0
4,NaN,NaN,NaN,NaN,NaN,4.0,2.0,5.0,4.0,1.0,...,5.0,1.0,5.0,3.0,4.0,4.0,2.0,2.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,Male,1.0,4.0,3.0,5.0,2.0,4.0,5.0,2.0,2.0,...,4.0,1.0,4.0,2.0,3.0,2.0,4.0,4.0,3.0,1.0
455,Female,1.0,4.0,1.0,3.0,3.0,3.0,2.0,5.0,4.0,...,4.0,4.0,2.0,5.0,3.0,3.0,3.0,2.0,2.0,2.0
456,Male,2.0,5.0,1.0,5.0,1.0,4.0,5.0,5.0,5.0,...,1.0,1.0,4.0,3.0,1.0,2.0,5.0,1.0,3.0,2.0
457,Male,4.0,4.0,4.0,5.0,2.0,2.0,2.0,2.0,4.0,...,2.0,1.0,2.0,1.0,3.0,4.0,4.0,3.0,4.0,5.0
458,Male,1.0,5.0,2.0,5.0,2.0,5.0,2.0,2.0,4.0,...,4.0,2.0,2.0,2.0,3.0,2.0,5.0,4.0,2.0,3.0

In [ ]:
# Viewing the first 5 rows
df.head(15)

,Sex,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
0,Female,1.0,2.0,1.0,5.0,2.0,3.0,1.0,5.0,4.0,...,4.0,2.0,4.0,3.0,4.0,1.0,2.0,1.0,2.0,4.0
1,Female,5.0,5.0,1.0,4.0,5.0,4.0,5.0,5.0,5.0,...,5.0,1.0,5.0,3.0,5.0,4.0,3.0,1.0,3.0,3.0
2,Male,2.0,5.0,1.0,3.0,3.0,2.0,5.0,1.0,5.0,...,2.0,2.0,3.0,4.0,2.0,5.0,3.0,2.0,1.0,2.0
3,Male,2.0,4.0,1.0,5.0,2.0,3.0,2.0,2.0,2.0,...,2.0,2.0,3.0,4.0,2.0,4.0,5.0,1.0,3.0,2.0
4,NaN,NaN,NaN,NaN,NaN,4.0,2.0,5.0,4.0,1.0,...,5.0,1.0,5.0,3.0,4.0,4.0,2.0,2.0,2.0,3.0
5,Male,5.0,5.0,1.0,2.0,3.0,2.0,2.0,4.0,5.0,...,5.0,2.0,5.0,3.0,3.0,5.0,4.0,1.0,1.0,2.0
6,Female,3.0,4.0,1.0,5.0,4.0,5.0,5.0,4.0,5.0,...,4.0,1.0,5.0,2.0,4.0,5.0,5.0,1.0,5.0,4.0
7,Male,1.0,4.0,2.0,4.0,2.0,5.0,2.0,1.0,1.0,...,4.0,2.0,3.0,3.0,5.0,5.0,3.0,2.0,3.0,3.0
8,Female,1.0,5.0,2.0,3.0,4.0,5.0,2.0,2.0,4.0,...,4.0,1.0,4.0,2.0,4.0,2.0,2.0,2.0,3.0,1.0
9,Female,2.0,5.0,1.0,5.0,2.0,3.0,2.0,5.0,5.0,...,4.0,2.0,5.0,1.0,3.0,2.0,5.0,1.0,2.0,4.0
10,Female,1.0,3.0,1.0,5.0,3.0,5.0,2.0,4.0,2.0,...,5.0,2.0,4.0,3.0,1.0,1.0,2.0,3.0,3.0,2.0
11,Male,2.0,4.0,3.0,4.0,4.0,3.0,2.0,1.0,2.0,...,1.0,2.0,2.0,2.0,3.0,2.0,4.0,3.0,2.0,NaN
12,Male,2.0,2.0,2.0,1.0,4.0,3.0,5.0,5.0,4.0,...,2.0,1.0,4.0,5.0,3.0,5.0,5.0,2.0,1.0,3.0
13,Female,2.0,1.0,1.0,3.0,3.0,2.0,2.0,5.0,1.0,...,2.0,1.0,5.0,4.0,2.0,5.0,5.0,1.0,4.0,3.0
14,Male,1.0,1.0,1.0,2.0,2.0,4.0,2.0,2.0,5.0,...,2.0,1.0,5.0,4.0,2.0,1.0,1.0,1.0,1.0,3.0

Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Item1'].plot(kind='hist', bins=20, title='Item1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Item2'].plot(kind='hist', bins=20, title='Item2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Item3'].plot(kind='hist', bins=20, title='Item3')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Sex').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='index', y='Item1', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Item1', y='Item2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Item2', y='Item3', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='Item3', y='Item4', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Item1']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Sex')):
  _plot_series(series, series_name, i)
  fig.legend(title='Sex', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Item1')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Item2']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Sex')):
  _plot_series(series, series_name, i)
  fig.legend(title='Sex', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Item2')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Item3']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Sex')):
  _plot_series(series, series_name, i)
  fig.legend(title='Sex', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Item3')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Item4']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Sex')):
  _plot_series(series, series_name, i)
  fig.legend(title='Sex', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Item4')

from matplotlib import pyplot as plt
_df_13['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['Item1'].plot(kind='line', figsize=(8, 4), title='Item1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['Item2'].plot(kind='line', figsize=(8, 4), title='Item2')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['Item3'].plot(kind='line', figsize=(8, 4), title='Item3')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['Sex'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='index', y='Sex', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_18['Sex'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_18, x='Item1', y='Sex', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['Sex'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='Item2', y='Sex', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['Sex'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='Item3', y='Sex', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
# Viewing the last 5 rows
df.tail(5)

,Sex,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
454,Male,1.0,4.0,3.0,5.0,2.0,4.0,5.0,2.0,2.0,...,4.0,1.0,4.0,2.0,3.0,2.0,4.0,4.0,3.0,1.0
455,Female,1.0,4.0,1.0,3.0,3.0,3.0,2.0,5.0,4.0,...,4.0,4.0,2.0,5.0,3.0,3.0,3.0,2.0,2.0,2.0
456,Male,2.0,5.0,1.0,5.0,1.0,4.0,5.0,5.0,5.0,...,1.0,1.0,4.0,3.0,1.0,2.0,5.0,1.0,3.0,2.0
457,Male,4.0,4.0,4.0,5.0,2.0,2.0,2.0,2.0,4.0,...,2.0,1.0,2.0,1.0,3.0,4.0,4.0,3.0,4.0,5.0
458,Male,1.0,5.0,2.0,5.0,2.0,5.0,2.0,2.0,4.0,...,4.0,2.0,2.0,2.0,3.0,2.0,5.0,4.0,2.0,3.0

In [ ]:
#Checking the structure of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 459 entries, 0 to 458
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sex     458 non-null    object
 1   Item1   448 non-null    float64
 2   Item2   448 non-null    float64
 3   Item3   448 non-null    float64
 4   Item4   448 non-null    float64
 5   Item5   450 non-null    float64
 6   Item6   446 non-null    float64
 7   Item7   446 non-null    float64
 8   Item8   446 non-null    float64
 9   Item9   447 non-null    float64
 10  Item10  451 non-null    float64
 11  Item11  451 non-null    float64
 12  Item12  451 non-null    float64
 13  Item13  450 non-null    float64
 14  Item14  450 non-null    float64
 15  Item15  450 non-null    float64
 16  Item16  449 non-null    float64
 17  Item17  450 non-null    float64
 18  Item18  450 non-null    float64
 19  Item19  450 non-null    float64
 20  Item20  450 non-null    float64
 21  Item21  450 non-null    float64
 22  Item22  450 non-null    float64
 23  Item23  450 non-null    float64
 24  Item24  451 non-null    float64
 25  Item25  455 non-null    float64
 26  Item26  453 non-null    float64
 27  Item27  452 non-null    float64
 28  Item28  451 non-null    float64
 29  Item29  451 non-null    float64
 30  Item30  451 non-null    float64
dtypes: float64(30), object(1)
memory usage: 111.3+ KB

In [ ]:
#Slicing the dataframe
#Slice column 3 to 5 with all of its observations
sub = df.iloc[:, 2:5]
sub

     Item2  Item3  Item4
0      2.0    1.0    5.0
1      5.0    1.0    4.0
2      5.0    1.0    3.0
3      4.0    1.0    5.0
4      NaN    NaN    NaN
..     ...    ...    ...
454    4.0    3.0    5.0
455    4.0    1.0    3.0
456    5.0    1.0    5.0
457    4.0    4.0    5.0
458    5.0    2.0    5.0

[459 rows x 3 columns]

In [ ]:
#slice dataframe to include columns 7-10 with all columns
#all records
subeme = df.iloc[:,6:9]
subeme

     Item6  Item7  Item8
0      3.0    1.0    5.0
1      4.0    5.0    5.0
2      2.0    5.0    1.0
3      3.0    2.0    2.0
4      2.0    5.0    4.0
..     ...    ...    ...
454    4.0    5.0    2.0
455    3.0    2.0    5.0
456    4.0    5.0    5.0
457    2.0    2.0    2.0
458    5.0    2.0    2.0

[459 rows x 3 columns]

In [ ]:
#Slice the data frame to only include observations index of 15 to 35
sub1 = df.iloc[15:36, :]
sub1

,Sex,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
15,Female,2.0,2.0,1.0,4.0,2.0,2.0,2.0,5.0,4.0,...,2.0,4.0,3.0,3.0,2.0,3.0,5.0,2.0,2.0,3.0
16,Female,2.0,4.0,4.0,3.0,3.0,2.0,2.0,4.0,5.0,...,1.0,3.0,5.0,5.0,3.0,4.0,4.0,4.0,5.0,3.0
17,Male,2.0,5.0,2.0,2.0,2.0,5.0,2.0,1.0,2.0,...,5.0,4.0,2.0,2.0,2.0,3.0,5.0,4.0,2.0,4.0
18,Male,2.0,4.0,1.0,4.0,3.0,4.0,5.0,1.0,2.0,...,1.0,2.0,4.0,4.0,2.0,3.0,5.0,2.0,3.0,2.0
19,Male,4.0,2.0,1.0,2.0,3.0,2.0,2.0,1.0,4.0,...,2.0,3.0,3.0,5.0,2.0,5.0,3.0,3.0,2.0,1.0
20,Male,5.0,3.0,1.0,1.0,3.0,1.0,2.0,5.0,5.0,...,5.0,1.0,3.0,1.0,3.0,3.0,3.0,2.0,1.0,2.0
21,Female,5.0,1.0,3.0,1.0,5.0,1.0,4.0,2.0,5.0,...,5.0,5.0,1.0,4.0,2.0,1.0,1.0,5.0,1.0,2.0
22,Male,5.0,4.0,1.0,3.0,2.0,4.0,5.0,5.0,2.0,...,4.0,1.0,5.0,1.0,3.0,3.0,1.0,1.0,5.0,2.0
23,Female,3.0,4.0,2.0,5.0,2.0,3.0,5.0,4.0,1.0,...,5.0,1.0,5.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0
24,Female,2.0,3.0,2.0,3.0,1.0,4.0,2.0,2.0,5.0,...,5.0,4.0,3.0,1.0,1.0,1.0,5.0,4.0,1.0,1.0
25,Female,3.0,2.0,1.0,1.0,1.0,1.0,5.0,5.0,4.0,...,5.0,1.0,4.0,5.0,2.0,2.0,2.0,1.0,2.0,1.0
26,Male,1.0,3.0,2.0,5.0,1.0,4.0,1.0,4.0,4.0,...,5.0,3.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,1.0
27,Male,1.0,2.0,2.0,4.0,3.0,2.0,2.0,4.0,1.0,...,1.0,2.0,5.0,1.0,3.0,4.0,3.0,1.0,2.0,2.0
28,Female,4.0,4.0,2.0,5.0,2.0,2.0,2.0,5.0,4.0,...,2.0,2.0,5.0,3.0,2.0,4.0,5.0,2.0,5.0,2.0
29,Female,5.0,2.0,3.0,2.0,4.0,1.0,2.0,2.0,2.0,...,5.0,2.0,2.0,2.0,2.0,3.0,4.0,5.0,3.0,4.0
30,Female,4.0,2.0,2.0,5.0,5.0,5.0,5.0,2.0,2.0,...,2.0,2.0,5.0,2.0,5.0,1.0,2.0,4.0,5.0,3.0
31,Male,1.0,3.0,1.0,2.0,3.0,3.0,1.0,4.0,5.0,...,1.0,1.0,2.0,3.0,3.0,2.0,2.0,3.0,1.0,3.0
32,Female,1.0,2.0,1.0,5.0,1.0,2.0,2.0,4.0,1.0,...,1.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0
33,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Male,2.0,2.0,1.0,2.0,2.0,3.0,5.0,4.0,5.0,...,2.0,1.0,5.0,4.0,2.0,3.0,5.0,1.0,2.0,2.0
35,Female,2.0,3.0,1.0,1.0,4.0,3.0,1.0,5.0,5.0,...,2.0,1.0,3.0,5.0,5.0,3.0,3.0,4.0,1.0,3.0

In [ ]:
#Checking for NAs or missing cases
df.isnull().values.any()

np.True_

In [ ]:
#Subset dataframe to include all rows that is made up of all missing cases
missing_df1= df[df.isnull().all(axis=1)] # take a subset to include all rows with missing cases
missing_df2= df[df.isnull().any(axis=1)] # take a subset to include any row with missing cases

In [ ]:
missing_df1.head()

Empty DataFrame
Columns: [Sex, Item1, Item2, Item3, Item4, Item5, Item6, Item7, Item8, Item9, Item10, Item11, Item12, Item13, Item14, Item15, Item16, Item17, Item18, Item19, Item20, Item21, Item22, Item23, Item24, Item25, Item26, Item27, Item28, Item29, Item30]
Index: []

[0 rows x 31 columns]

In [ ]:
missing_df2.head()

,Sex,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
4,NaN,NaN,NaN,NaN,NaN,4.0,2.0,5.0,4.0,1.0,...,5.0,1.0,5.0,3.0,4.0,4.0,2.0,2.0,2.0,3.0
11,Male,2.0,4.0,3.0,4.0,4.0,3.0,2.0,1.0,2.0,...,1.0,2.0,2.0,2.0,3.0,2.0,4.0,3.0,2.0,NaN
33,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,4.0,4.0,2.0,2.0,3.0
51,Female,1.0,2.0,3.0,4.0,2.0,4.0,2.0,2.0,1.0,...,5.0,2.0,4.0,4.0,2.0,NaN,NaN,NaN,NaN,4.0

In [ ]:
#Subset dataframe to include all rows with complete cases
complete_df= df[df.notnull().all(axis=1)]
complete_df.isnull().values.any()

np.False_

In [ ]:
complete_df.head()

,Sex,Item1,Item2,Item3,Item4,Item5,Item6,Item7,Item8,Item9,...,Item21,Item22,Item23,Item24,Item25,Item26,Item27,Item28,Item29,Item30
0,Female,1.0,2.0,1.0,5.0,2.0,3.0,1.0,5.0,4.0,...,4.0,2.0,4.0,3.0,4.0,1.0,2.0,1.0,2.0,4.0
1,Female,5.0,5.0,1.0,4.0,5.0,4.0,5.0,5.0,5.0,...,5.0,1.0,5.0,3.0,5.0,4.0,3.0,1.0,3.0,3.0
2,Male,2.0,5.0,1.0,3.0,3.0,2.0,5.0,1.0,5.0,...,2.0,2.0,3.0,4.0,2.0,5.0,3.0,2.0,1.0,2.0
3,Male,2.0,4.0,1.0,5.0,2.0,3.0,2.0,2.0,2.0,...,2.0,2.0,3.0,4.0,2.0,4.0,5.0,1.0,3.0,2.0
5,Male,5.0,5.0,1.0,2.0,3.0,2.0,2.0,4.0,5.0,...,5.0,2.0,5.0,3.0,3.0,5.0,4.0,1.0,1.0,2.0

In [ ]:
#Getting a simple descriptives for incomplete and complete records
desc1 = df.describe()
desc2 =  complete_df.describe()

In [ ]:
desc1.T

        count      mean       std  min  25%  50%  75%  max
Item1   448.0  2.395089  1.347024  1.0  1.0  2.0  3.0  5.0
Item2   448.0  3.044643  1.223472  1.0  2.0  3.0  4.0  5.0
Item3   448.0  1.866071  0.992099  1.0  1.0  2.0  2.0  5.0
Item4   448.0  3.459821  1.357123  1.0  2.0  4.0  5.0  5.0
Item5   450.0  2.475556  1.016820  1.0  2.0  2.0  3.0  5.0
Item6   446.0  3.152466  1.289223  1.0  2.0  3.0  4.0  5.0
Item7   446.0  2.896861  1.551553  1.0  2.0  2.0  5.0  5.0
Item8   446.0  3.125561  1.545540  1.0  2.0  4.0  5.0  5.0
Item9   447.0  3.111857  1.573610  1.0  2.0  4.0  5.0  5.0
Item10  451.0  3.015521  1.653879  1.0  2.0  2.0  5.0  5.0
Item11  451.0  2.880266  1.581514  1.0  2.0  2.0  5.0  5.0
Item12  451.0  3.716186  1.525831  1.0  2.0  4.0  5.0  5.0
Item13  450.0  3.782222  1.555691  1.0  2.0  5.0  5.0  5.0
Item14  450.0  2.997778  1.574432  1.0  2.0  2.0  5.0  5.0
Item15  450.0  2.786667  1.633120  1.0  1.0  2.0  5.0  5.0
Item16  449.0  2.530067  1.558276  1.0  1.0  2.0  4.0  5.0
Item17  450.0  2.940000  1.564771  1.0  2.0  2.0  5.0  5.0
Item18  450.0  3.537778  1.565111  1.0  2.0  4.0  5.0  5.0
Item19  450.0  3.226667  1.631319  1.0  2.0  4.0  5.0  5.0
Item20  450.0  2.873333  1.656317  1.0  2.0  2.0  5.0  5.0
Item21  450.0  3.300000  1.600738  1.0  2.0  4.0  5.0  5.0
Item22  450.0  1.975556  1.056037  1.0  1.0  2.0  2.0  5.0
Item23  450.0  3.342222  1.327538  1.0  2.0  3.0  5.0  5.0
Item24  451.0  2.955654  1.286782  1.0  2.0  3.0  4.0  5.0
Item25  455.0  2.657143  1.122962  1.0  2.0  3.0  3.0  5.0
Item26  453.0  2.688742  1.174124  1.0  2.0  3.0  3.0  5.0
Item27  452.0  3.595133  1.243082  1.0  3.0  4.0  5.0  5.0
Item28  451.0  2.235033  1.134398  1.0  1.0  2.0  3.0  5.0
Item29  451.0  2.445676  1.161818  1.0  2.0  2.0  3.0  5.0
Item30  451.0  2.312639  1.075916  1.0  1.0  2.0  3.0  5.0

In [ ]:
desc2.T

        count      mean       std  min  25%  50%  75%  max
Item1   436.0  2.383028  1.343383  1.0  1.0  2.0  3.0  5.0
Item2   436.0  3.057339  1.225745  1.0  2.0  3.0  4.0  5.0
Item3   436.0  1.855505  0.991802  1.0  1.0  2.0  2.0  5.0
Item4   436.0  3.463303  1.358171  1.0  2.0  4.0  5.0  5.0
Item5   436.0  2.474771  1.020167  1.0  2.0  2.0  3.0  5.0
Item6   436.0  3.158257  1.293734  1.0  2.0  3.0  4.0  5.0
Item7   436.0  2.910550  1.551796  1.0  2.0  2.0  5.0  5.0
Item8   436.0  3.121560  1.549607  1.0  2.0  4.0  5.0  5.0
Item9   436.0  3.126147  1.566944  1.0  2.0  4.0  5.0  5.0
Item10  436.0  3.025229  1.653087  1.0  2.0  2.0  5.0  5.0
Item11  436.0  2.896789  1.581761  1.0  2.0  2.0  5.0  5.0
Item12  436.0  3.733945  1.529133  1.0  2.0  4.0  5.0  5.0
Item13  436.0  3.818807  1.542267  1.0  2.0  5.0  5.0  5.0
Item14  436.0  2.995413  1.574211  1.0  2.0  2.0  5.0  5.0
Item15  436.0  2.805046  1.629067  1.0  1.0  2.0  5.0  5.0
Item16  436.0  2.511468  1.557291  1.0  1.0  2.0  4.0  5.0
Item17  436.0  2.917431  1.558829  1.0  2.0  2.0  5.0  5.0
Item18  436.0  3.527523  1.568856  1.0  2.0  4.0  5.0  5.0
Item19  436.0  3.240826  1.631383  1.0  2.0  4.0  5.0  5.0
Item20  436.0  2.887615  1.657788  1.0  2.0  2.0  5.0  5.0
Item21  436.0  3.295872  1.596571  1.0  2.0  4.0  5.0  5.0
Item22  436.0  1.974771  1.059953  1.0  1.0  2.0  2.0  5.0
Item23  436.0  3.350917  1.335036  1.0  2.0  3.0  5.0  5.0
Item24  436.0  2.974771  1.281811  1.0  2.0  3.0  4.0  5.0
Item25  436.0  2.660550  1.126240  1.0  2.0  3.0  3.0  5.0
Item26  436.0  2.692661  1.167389  1.0  2.0  3.0  3.0  5.0
Item27  436.0  3.614679  1.240380  1.0  3.0  4.0  5.0  5.0
Item28  436.0  2.224771  1.136614  1.0  1.0  2.0  3.0  5.0
Item29  436.0  2.431193  1.161584  1.0  2.0  2.0  3.0  5.0
Item30  436.0  2.284404  1.068605  1.0  1.0  2.0  3.0  5.0

In [ ]:
%pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=1.47 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)
Downloading pyreadstat-1.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (666 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 666.4/666.4 kB 8.9 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.1