# <font face = 'Impact' color = '#FFAEBC' > Exercise on Loading, Organizing, and Storing Data<font/>
#### <font face = 'Times New Roman' color = '#B5E5CF'> Licence: GPL v3.0 <font/>
#### <font face = 'Times New Roman' color = '#B5E5CF'> Author and Trainer: Paolo Hilado MSc. (Data Science) <font/>
Showcase your learning and skills by accomplishing this jupyter notebook. Follow through each of the tasks and code with python to address them.

## <font face = 'Times New Roman' color = '#ff99c8'> Submitted by: Rimalyn M. Magallamento <font/>
#### <font face = 'Times New Roman' color = '#e4c1f9'> Year Level and Section: BSIS-4B <font/>
#### <font face = 'Times New Roman' color = '#d0f4de'> Date: September 5, 2025 <font/>

In [ ]:
pip install researchpy

Requirement already satisfied: researchpy in /usr/local/lib/python3.12/dist-packages (0.3.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from researchpy) (1.16.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from researchpy) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from researchpy) (2.2.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from researchpy) (0.14.5)
Requirement already satisfied: patsy in /usr/local/lib/python3.12/dist-packages (from researchpy) (1.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->researchpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->researchpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->researchpy) (2025.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels->researchpy) (25.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->researchpy) (1.17.0)

In [ ]:
# Import the necesary libraries such as pandas, researchpy, os, and numpy.
import pandas as pd
import numpy as np
import researchpy as rp
import os

In [ ]:
#Checking out the current working directory
print(os.getcwd())

/content/sample_data

In [ ]:
#Load a spreadsheet and assigning it to a variable df.
# Open and work on "ExperimentOne.xlsx".
os.chdir('/content/sample_data/')
df = pd.read_excel('ExperimentOne.xlsx')

In [ ]:
#View the dataframe
df

    ID   Post  Group
0    1  17.23  Cntrl
1    2  16.04  Cntrl
2    3  19.22  Cntrl
3    4  19.45  Cntrl
4    5  18.53  Cntrl
..  ..    ...    ...
69  70   6.86     Tx
70  71  17.63     Tx
71  72  18.84     Tx
72  73  15.11     Tx
73  74  19.07     Tx

[74 rows x 3 columns]

In [ ]:
# Viewing the first 7 rows
df.head(7)

   ID   Post  Group
0   1  17.23  Cntrl
1   2  16.04  Cntrl
2   3  19.22  Cntrl
3   4  19.45  Cntrl
4   5  18.53  Cntrl
5   6  21.00  Cntrl
6   7  19.28  Cntrl

In [ ]:
# Viewing the last 7 rows
df.tail(7)

    ID   Post Group
67  68  12.55    Tx
68  69  19.67    Tx
69  70   6.86    Tx
70  71  17.63    Tx
71  72  18.84    Tx
72  73  15.11    Tx
73  74  19.07    Tx

In [ ]:
# Slice the data frame to only show the data on the "Post" Column.
sub = df.iloc[:, 1]

In [ ]:
# Create different subsets of the data frame and show it.
# Get the data for the first column
sub1 = df.iloc[:, 0]
sub2 = df.iloc[:, 1]
sub3 = df.iloc[:, 2]

print(sub1, sub2, sub3)

0      1
1      2
2      3
3      4
4      5
      ..
69    70
70    71
71    72
72    73
73    74
Name: ID, Length: 74, dtype: int64 0     17.23
1     16.04
2     19.22
3     19.45
4     18.53
      ...
69     6.86
70    17.63
71    18.84
72    15.11
73    19.07
Name: Post, Length: 74, dtype: float64 0     Cntrl
1     Cntrl
2     Cntrl
3     Cntrl
4     Cntrl
      ...
69       Tx
70       Tx
71       Tx
72       Tx
73       Tx
Name: Group, Length: 74, dtype: object

In [ ]:
# Get the Post Test and Group data for records 1-10
sub4 = df.iloc[1:11, 1:3]
sub4

     Post  Group
1   16.04  Cntrl
2   19.22  Cntrl
3   19.45  Cntrl
4   18.53  Cntrl
5   21.00  Cntrl
6   19.28  Cntrl
7   19.63  Cntrl
8   12.66  Cntrl
9   17.55  Cntrl
10  18.08  Cntrl

In [ ]:
# Get the Post Test and Group data for records 7,11,15,50,61.
sub4 = df.iloc[[7,11,15,50,61], 1:3]
sub4

     Post  Group
7   19.63  Cntrl
11  16.55  Cntrl
15  21.04  Cntrl
50  18.58     Tx
61  16.41     Tx

In [ ]:
# Check the information of the data frame such as number of records and features,
# data types of each feature and file size.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      74 non-null     int64
 1   Post    74 non-null     float64
 2   Group   74 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.9+ KB

In [ ]:
#Checking for NAs or missing cases for the data set
df.isnull().values.any()

np.False_

In [ ]:
# Check for NAs per column
complete_df= df[df.notnull().all(axis=1)]
complete_df.isnull().values.any()

np.False_

In [ ]:
# Provide a descriptive analysis for the Post Test measure
desc1 = df.describe()
desc1.T

      count       mean        std   min     25%     50%    75%    max
ID     74.0  37.500000  21.505813  1.00  19.250  37.500  55.75  74.00
Post   74.0  16.924324   3.344020  5.28  16.055  18.205  19.16  21.04

In [ ]:
# Provide a descriptive analysis for Post Test measure per Group.
# Make sure that it is rounded to two decimal places only.
# Save this in the variable labeled results.
# Present the results variable
desc1 = df.groupby('Group').describe()
result = desc1.round(2)
result

         ID                                             Post               \
      count  mean    std   min   25%   50%   75%   max count   mean   std
Group
Cntrl  37.0  19.0  10.82   1.0  10.0  19.0  28.0  37.0  37.0  17.23  3.52
Tx     37.0  56.0  10.82  38.0  47.0  56.0  65.0  74.0  37.0  16.62  3.17


        min    25%    50%    75%    max
Group
Cntrl  5.28  16.24  19.05  19.42  21.04
Tx     6.86  16.01  17.63  18.55  20.83

Journal on Activity Exercise One

What were the problems that you encountered while accomplishing this exercise?
- I just encoutered some errors on the code and, there are parts that I had a bit of a hard time figure out the code but, it turned out well after.

Cite the reasons why you had these problems while dooing the task.
- I think I lack on knowledge on some of the pre-built codes that is why I struggled.

List down your next set of actions so as not to encounter these problems again.

- I will try and learn some tips and trick through Youtube videos. I will also practice it hands-on on my laptop to be able to master it.